openapi: 3.0.0
info:
  title: Jobs API
  version: 1.0.0
servers:
  - url: "https://jobs-api-production-9660.up.railway.app"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    apikeyAuth:
      type: http
      scheme: apikey
tags:
  - name: Auth
  - name: Jobs
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Darkness
                email: darkness@gmail.com
                password: "123456"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: darkness@gmail.com
                password: "123456"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/jobs:
    get:
      tags:
        - Jobs
      summary: All Jobs
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Jobs
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: facebook
                position: intern
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

  /api/v1/jobs/{id}:
    get:
      tags:
        - Jobs
      summary: Single Job
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Jobs
      summary: Update Job
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: ""
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: Delete Job
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
